initial implementation
creamlaflare/go-project-sprint-9 pull request #1
Opened 2024-04-17 22:45 UTC by creamlaflare

2024-04-18 20:59 UTC, dirtymew requested changes
Привет Антон

Отличная работа - но есть что поправить - см PR

2024-04-18 20:59 UTC, dirtymew commented on main.go
> +	if inputSum.Load() != sum {
а тут зачем load? у нас разве может быть конкурентный доступ?

2024-04-18 20:59 UTC, dirtymew commented on main.go
> +		cancel()
зачем?  есть же defer cancel()

2024-04-18 20:59 UTC, dirtymew commented on main.go
> +	ticker := time.NewTicker(time.Millisecond)
тут неверно - нудно получить из канала потом отправить и подождать 

а тут ты раз в милисекунду читаешь их канала - это не тоже самое

2024-04-18 20:59 UTC, dirtymew commented on main.go
> +			close(out)
для такого удобнее defer  использовать

2024-04-18 20:59 UTC, dirtymew commented on main.go
> +			close(ch)
тут тоже лучше в defer  канал закрывать

2024-04-18 20:59 UTC, dirtymew commented on main.go
> +	var inputCount atomic.Int64 // количество сгенерированных чисел
отлично что испрользовал atomic

2024-04-21 23:17 UTC, dirtymew approved these changes
Привет Антон

работа выполнена - зачет

обрати внимание на комментарии в PR

2024-04-21 23:17 UTC, dirtymew commented on main.go
> +		<-ticker.C
тут перемудрил - time.Sleep достаточно было бы

2024-04-21 23:17 UTC, dirtymew commented on main.go
> +	ctx := context.Background()
лишняя переменная

2024-04-21 23:17 UTC, dirtymew commented on main.go
> +		cancel()
@creamlaflare  - ты зарезолвил тред и ничего не поменял ? так обычно в ревью не поступают...

2024-04-21 23:17 UTC, dirtymew commented on main.go
> +	for _, v := range amounts {
зачем тут второй цикл? одного достаточно

2024-04-21 23:23 UTC, creamlaflare commented on main.go
> +		cancel()
@dirtymew я по мере выполнения на локале резолвлю, так удобнее просто сверят с тем что я сделал и что осталось исправить

2024-04-21 23:35 UTC, merged